on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
      - name: Cache Docker Image
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-docker-${{ hashFiles('acceptance-test.Dockerfile', 'acceptance-test.Dockerfile.dockerignore') }}
          path: .cache/docker
          restore-keys: |
            ${{ runner.os }}-docker-${{ hashFiles('acceptance-test.Dockerfile', 'acceptance-test.Dockerfile.dockerignore') }}
            ${{ runner.os }}-docker-
      - name: Test
        run: make test
